name: pr_unit_test
on:
    pull_request:
        branches:
            - main
        types: [opened, reopened, synchronize]

jobs:
    unit-test:
        runs-on: ubuntu-latest
        name: Run unit tests

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup JDK environment
              uses: actions/setup-java@v4
              with:
                  distribution: "zulu"
                  java-version: 17
                  cache: 'gradle'

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v4

            - name: Run tests
              run: ./gradlew test

            - name: Generate coverage report
              run: ./gradlew jacocoCoreDebugCodeCoverage

            - name: Add coverage to PR
              id: jacoco
              uses: madrapps/jacoco-report@v1.7.1
              with:
                  paths: |
                      ${{ github.workspace }}/**/build/reports/jacoco/jacocoCoreDebugCodeCoverage/jacocoCoreDebugCodeCoverage.xml
                  token: ${{ secrets.GITHUB_TOKEN }}
                  min-coverage-overall: 40
                  min-coverage-changed-files: 60
                  update-comment: true
